export default defineAppConfig({
  pages: [
    "pages/login/index",
    "pages/home/index",
    "pages/index/index",
    "pages/page2/index",
    "pages/manPowerCollection/index",
    "pages/manPowerCollection/myWorkInfo/index",
    "pages/manPowerCollection/myWorkInfo/pages/assistanceInfo/index",
    "pages/manPowerCollection/myWorkInfo/pages/baseInfo/index",
    "pages/manPowerCollection/myWorkInfo/pages/chooseEducation/index",
    "pages/manPowerCollection/myWorkInfo/pages/employInfo/index",
    "pages/manPowerCollection/myWorkInfo/pages/identifyInfo/index",
    "pages/manPowerCollection/myWorkInfo/pages/identifyPicture/index",
    "pages/manPowerCollection/myWorkInfo/pages/trainInfo/index",
    "pages/manPowerCollection/personalCenter/pages/authentication/index",
    "pages/manPowerCollection/personalCenter/pages/employDetail/index",
    "pages/manPowerCollection/personalCenter/pages/employList/index",
    "pages/manPowerCollection/personalCenter/pages/login/index",
  ],
  window: {
    backgroundTextStyle: "light",
    navigationBarBackgroundColor: "#fff",
    navigationBarTitleText: "WeChat",
    navigationBarTextStyle: "black",
  },
});
